name: Release
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Type of release (release or prerelease)'
        required: true
        default: 'release'
      nodeVersion:
        description: 'Node.js version'
        required: true
        default: '18'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.event.inputs.nodeVersion }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install semantic-release and plugins
        run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.releaseType }}" = "prerelease" ]; then
            semantic-release --branches={ name: 'develop', prerelease: true, channel: 'develop' }
          else
            semantic-release
          fi
